'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CelebrityBirthday.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anniv_.
        '''</summary>
        Friend ReadOnly Property ANNIVERSARY() As String
            Get
                Return ResourceManager.GetString("ANNIVERSARY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Birthdays_.
        '''</summary>
        Friend ReadOnly Property BIRTHDAY() As String
            Get
                Return ResourceManager.GetString("BIRTHDAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BOTSD_.
        '''</summary>
        Friend ReadOnly Property BOTSD() As String
            Get
                Return ResourceManager.GetString("BOTSD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;br&gt;.
        '''</summary>
        Friend ReadOnly Property BREAK() As String
            Get
                Return ResourceManager.GetString("BREAK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property cake() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cake", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cake_with_candle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cake_with_candle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complete.
        '''</summary>
        Friend ReadOnly Property COMPLETE() As String
            Get
                Return ResourceManager.GetString("COMPLETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copyicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copyicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;.
        '''</summary>
        Friend ReadOnly Property DOUBLEQUOTES() As String
            Get
                Return ResourceManager.GetString("DOUBLEQUOTES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global Settings.
        '''</summary>
        Friend ReadOnly Property GLOBAL_SETTINGS() As String
            Get
                Return ResourceManager.GetString("GLOBAL_SETTINGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property id() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("id", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Id not found.
        '''</summary>
        Friend ReadOnly Property ID_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("ID_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Table From Database.
        '''</summary>
        Friend ReadOnly Property LOADING_TABLE() As String
            Get
                Return ResourceManager.GetString("LOADING_TABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next WP Number.
        '''</summary>
        Friend ReadOnly Property NEXTWPNO() As String
            Get
                Return ResourceManager.GetString("NEXTWPNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No close bracket.
        '''</summary>
        Friend ReadOnly Property NO_CLOSE_BRACKET() As String
            Get
                Return ResourceManager.GetString("NO_CLOSE_BRACKET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No load date available.
        '''</summary>
        Friend ReadOnly Property NO_LOAD_DATE() As String
            Get
                Return ResourceManager.GetString("NO_LOAD_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No open bracket.
        '''</summary>
        Friend ReadOnly Property NO_OPEN_BRACKET() As String
            Get
                Return ResourceManager.GetString("NO_OPEN_BRACKET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot identify a single record.
        '''</summary>
        Friend ReadOnly Property NO_SINGLE_RECORD() As String
            Get
                Return ResourceManager.GetString("NO_SINGLE_RECORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NoImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;nbsp;.
        '''</summary>
        Friend ReadOnly Property NON_BREAKING_SPACE() As String
            Get
                Return ResourceManager.GetString("NON_BREAKING_SPACE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pasteicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pasteicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rewrite File.
        '''</summary>
        Friend ReadOnly Property REWRITE_FILE() As String
            Get
                Return ResourceManager.GetString("REWRITE_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RTB.
        '''</summary>
        Friend ReadOnly Property RTB() As String
            Get
                Return ResourceManager.GetString("RTB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SingleTweetImage.
        '''</summary>
        Friend ReadOnly Property SINGLE_TWEET() As String
            Get
                Return ResourceManager.GetString("SINGLE_TWEET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /.
        '''</summary>
        Friend ReadOnly Property SLASH() As String
            Get
                Return ResourceManager.GetString("SLASH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text.
        '''</summary>
        Friend ReadOnly Property TEXT() As String
            Get
                Return ResourceManager.GetString("TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Today.
        '''</summary>
        Friend ReadOnly Property TODAY() As String
            Get
                Return ResourceManager.GetString("TODAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tweet of the Day.
        '''</summary>
        Friend ReadOnly Property TOTD() As String
            Get
                Return ResourceManager.GetString("TOTD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;nbsp;&amp;nbsp;.
        '''</summary>
        Friend ReadOnly Property TWO_SPACES() As String
            Get
                Return ResourceManager.GetString("TWO_SPACES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown signature type.
        '''</summary>
        Friend ReadOnly Property UNKNOWN_SIG() As String
            Get
                Return ResourceManager.GetString("UNKNOWN_SIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://en.wikipedia.org/wiki/.
        '''</summary>
        Friend ReadOnly Property WIKIURL() As String
            Get
                Return ResourceManager.GetString("WIKIURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;a href=.
        '''</summary>
        Friend ReadOnly Property WP_A_HREF() As String
            Get
                Return ResourceManager.GetString("WP_A_HREF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/a&gt;.
        '''</summary>
        Friend ReadOnly Property WP_END_A() As String
            Get
                Return ResourceManager.GetString("WP_END_A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- /wp:paragraph --&gt;.
        '''</summary>
        Friend ReadOnly Property WP_END_PARA() As String
            Get
                Return ResourceManager.GetString("WP_END_PARA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!-- wp:paragraph --&gt;.
        '''</summary>
        Friend ReadOnly Property WP_PARA() As String
            Get
                Return ResourceManager.GetString("WP_PARA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://celebritybirthday.files.wordpress.com/.
        '''</summary>
        Friend ReadOnly Property WPFILESURL() As String
            Get
                Return ResourceManager.GetString("WPFILESURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://celebritybirthday.wordpress.com/.
        '''</summary>
        Friend ReadOnly Property WPPAGEURL() As String
            Get
                Return ResourceManager.GetString("WPPAGEURL", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
